<!DOCTYPE html>
<html lang="zh-CN">
   <?php require $viewPath . "common/head.phtml"?>
<body>
<section id="container" >
    <?php require $viewPath . "common/nav.phtml"?>
    <?php require $viewPath . "common/sidebar.phtml"?>
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            <div class="row mt">
                <div class="col-md-12">
                    <div class="content-panel">
                        <h4>
                            <i class="fa fa-angle-right"></i> 案件元素
                            <?php if (isset($currentMenu[200201])) {?>
                            <button data-toggle="modal" href="#myModal" class="btn btn-primary pull-right nav-right">  添加 </button>
                            <?php }?>
                        </h4>
                        <hr>
                        <table class="table table-striped table-advance table-hover">
                        <thead>
                            <tr>
                                <th data-field="name"><i class="fa fa-bookmark"></i> 名称</th>
                                <th data-field="name"><i class="fa fa-bars"></i> 类型</th>
                                <th data-field="operator"><i class="fa fa-user"></i> 添加人</th>
                                <th data-field="created"><i class="fa fa-clock-o"></i> 添加时间</th>
                                <th><i class="fa fa-cogs"> 操作</i></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($result)){?>
                            <tr>
                                <td colspan="4" style="text-align:center"> 没有找到数据</td>
                            </tr>
                            <?php } else {
                                foreach ($result as $k=>$v) { 
                                    $datas = $v;
                            ?>
                            <tr>
                                <td><?php echo $v['name'];?></td>
                                <td><?php echo $v['level_zh'];?></td>
                                <td><?php echo  $datas['parentname'];?></td>
                                <td><?php echo $operators[$v['operator']]['name'];?></td>
                                <td><?php echo $v['created'];?></td>
                                <td>
                                    <button class="btn btn-primary btn-xs modifyButton" title="修改" datas='<?php echo json_encode($datas)?>'><i class="fa fa-pencil"></i></button>
                                </td>
                            </tr>
                            <?php }}?>
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
    <?php require $viewPath . "common/footer.phtml"?>
</section>
<?php require $viewPath . "common/js.phtml"?>
<?php if (isset($currentMenu[200203])) {?>
<form class="form-horizontal style-form" id="modifyForm" onSubmit="return false;">
    <div aria-hidden="true" aria-labelledby="modifyModalLabel" role="dialog" tabindex="-1" id="modifyModal" class="modal fade">
        <input type="hidden" name="id">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  修改案件类型 </h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <br />
                    <div class="from-group form-inline">
                        <input type="text" name="name" placeholder="名称" autocomplete="off" class="form-control placeholder-no-fix">
                        <div class="btn-group">
                            <input type="hidden" name="level" id="level">
                            <button type="button" class="btn btn-theme03" id="level-btn">层级</button>
                            <button type="button" class="btn btn-theme03 dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a class="a-level" data-id="1" href="#bottom"> 一 </a></li>
                                <li><a class="a-level" data-id="2" href="#bottom"> 二 </a></li>
                                <li><a class="a-level" data-id="3" href="#bottom"> 三 </a></li>
                                <li><a class="a-level" data-id="4" href="#bottom"> 四 </a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <input type="hidden" name="parentid" id="parentid">
                            <button type="button" class="btn btn-theme03" id="parent-btn">上级</button>
                            <button type="button" class="btn btn-theme03 dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only"></span>
                            </button>
                            <ul class="dropdown-menu pLevel" role="menu">
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="modifySubmitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>

<?php if (isset($currentMenu[200202])) {?>
<form class="form-horizontal style-form" id="form" onSubmit="return false;">
    <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  添加案件元素</h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <br />
                    <div class="from-group form-inline">
                        <input type="text" name="name" placeholder="名称" autocomplete="off" class="form-control placeholder-no-fix">
                        <div class="btn-group pull-right nav-right">
                            <input type="hidden" name="need[]" value='2'>
                            <button type="button" class="btn btn-theme04" id="need-btn">选填</button>
                            <button type="button" class="btn btn-theme04 dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a class="a-need" data-id="1" href="#bottom"> 必填</a></li>
                                <li><a class="a-need" data-id="2" href="#bottom"> 选填</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <input type="hidden" name="parentid" id="parentid">
                            <button type="button" class="btn btn-theme03" id="type-btn">类型</button>
                            <button type="button" class="btn btn-theme03 dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only"></span>
                            </button>
                            <ul class="dropdown-menu pLevel" role="menu">
                                <li><a class="a-type" data-id="1" href="#bottom"> input</a></li>
                                <li><a class="a-type" data-id="2" href="#bottom"> textarea</a></li>
                                <li><a class="a-type" data-id="3" href="#bottom"> select</a></li>
                                <li><a class="a-type" data-id="4" href="#bottom"> calendar</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="submitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>
<script type="text/javascript" src="/public/js/base.js"></script>
<script>
function onComplete(result){
    if (result.status != 200) {
        $('.alert-warning').show();
        $('.showMsg').html(result.msg);
    } else {
        location.href = "/sys/cfields";
    }
}
$(document).ready(function(){
    $('#myModal .a-need').live("click", function(){
        var obj = $(this).parent().parent().parent();
        var val = $(this).html();
        var id  =  $(this).attr('data-id');
        obj.find('button[id="need-btn"]').html(val)
        obj.find('input[name="need[]"]').val(id)
    });
    $('#submitForm').click(function(){
        ajaxPost('/sys/cfields/act/create', $("#form").serialize());
    });
})
</script>
</body>
</html>
