<!DOCTYPE html>
<html lang="zh-CN">
   <?php require $viewPath . "common/head.phtml"?>
<body>
<section id="container" >
    <?php require $viewPath . "common/nav.phtml"?>
    <?php require $viewPath . "common/sidebar.phtml"?>
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            <div class="row mt">
                <div class="col-md-12">
                    <div class="content-panel">
                        <div class="clearfix"></div>
                        <h4><i class="fa fa-angle-right"></i> 职位列表
                        <?php if (isset($currentMenu[500201])) {?>
                        <button data-toggle="modal" href="#myModal" class="btn btn-primary pull-right nav-right">  添加 </button>
                        <?php }?>
                        </h4>
                        <hr>
                        <table class="table table-striped table-advance table-hover">
                        <thead>
                            <tr>
                                <th><i class="fa fa-flag"></i> 名称</th>
                                <th><i class="fa fa-user"></i> 添加人</th>
                                <th><i class="fa fa-clock-o"></i> 添加时间</th>
                                <th><i class="fa fa-cogs"> 操作</i></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($result as $k=>$v) {?>
                              <tr>
                                <td><?php echo $v['name'];?></td>
                                <td><?php echo $operators[$v['operator']]['name'];?></td>
                                <td><?php echo $v['created'];?></td>
                                <td>
                                    <?php if (isset($currentMenu[500502])) {?>
                                    <button class="btn btn-primary btn-xs modifyButton" data-name='<?php echo $v['name']?>' data-id='<?php echo $v['id']?>' data-rid='<?php echo $v['resourceid']?>' href="#modifyModal" title="修改"><i class="fa fa-pencil"></i></button>
                                    <?php }?>
                                </td>
                              </tr>
                            <?php }?>
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
    <?php require $viewPath . "common/footer.phtml"?>
</section>
<!-- modal -->
<?php require $viewPath . "common/js.phtml"?>
<!-- Modal -->
<?php if (isset($currentMenu[500502])) {?>
<form class="form-horizontal style-form" id="form" onSubmit="return false;">
    <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  添加职位</h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <br />
                    <div class="">
                        <input type="text" name="name" placeholder="职位名称" autocomplete="off" class="form-control placeholder-no-fix">
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="submitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>

<?php if (isset($currentMenu[500503])) {?>
<form class="form-horizontal style-form" id="modifyForm" onSubmit="return false;">
    <input type="hidden" name='dutiesid' id="dutiesid">
    <div aria-hidden="true" aria-labelledby="modifyModalLabel" role="dialog" tabindex="-1" id="modifyModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  修改职位</h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <br />
                    <div class="">
                    <input type="text" id="modifyName" name="name" placeholder="职位名称" autocomplete="off" class="form-control placeholder-no-fix">
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="modifySubmitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>
<script type="text/javascript" src="/public/js/base.js"></script>
<script>
function onComplete(result){
    if (result.status != 200) {
        $('.alert-warning').show();
        $('.showMsg').html(result.msg);
    } else {
        location.href = "/sys/duties";
    }
}
$(document).ready(function(){
    $('#submitForm').click(function(){
        ajaxPost('/sys/duties/act/create', $("#form").serialize());
    });
    $('#modifySubmitForm').click(function(){
        ajaxPost('/sys/duties/act/modify', $("#modifyForm").serialize());
    });
    $(".modifyButton").click(function(){
        $('#modifyName').val($(this).attr('data-name'));
        $('#dutiesid').val($(this).attr('data-id'));
        var resourceid = $(this).attr('data-rid').split(',');
        var obj = $("#modifyModal input[name='ids[]']");
        obj.each(function(i){
            var value = $(this).attr('value');
            if ($.inArray(value, resourceid) > -1) {
                $(this).attr('checked', true);
            } else {
                $(this).attr('checked', false);
            }
        })
        $('#modifyModal').modal('show');
    });
})
</script>
</body>
</html>
