<!DOCTYPE html>
<html lang="zh-CN">
   <?php require $viewPath . "common/head.phtml"?>
<body>
<section id="container" >
    <?php require $viewPath . "common/nav.phtml"?>
    <?php require $viewPath . "common/sidebar.phtml"?>
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            <div class="row mt">
                <div class="col-md-12">
                    <div class="content-panel">
                        <div class="clearfix"></div>
                        <h4><i class="fa fa-angle-right"></i> 权限列表  <button data-toggle="modal" href="#myModal" class="btn btn-primary pull-right nav-right"> 添加 </button></h4>
                        <hr>
                        <table class="table table-striped table-advance table-hover">
                        <thead>
                            <tr>
                                <th data-field="name"><i class="fa fa-bookmark"></i> 姓名 </th>
                                <th data-field="duties"><i class="fa fa-user-secret"></i> 职位</th>
                                <th data-field="role"><i class="fa fa-flag"></i> 角色</th>
                                <th data-field="mobile"><i class="fa fa-phone"></i> 电话</th>
                                <th data-field="email"><i class="fa fa-envelope"></i> 邮箱</th>
                                <th data-field="operator"><i class="fa fa-user"></i> 添加人</th>
                                <th data-field="created"><i class="fa fa-clock-o"></i> 添加时间</th>
                                <th data-field="status"><i class="fa fa-heart"></i> 状态</th>
                                <th><i class="fa fa-cogs"> 操作</i></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($result as $k=>$v) {?>
                              <tr>
                                <td><?php echo $v['name'];?></td>
                                <td><?php echo $v['duties'];?></td>
                                <td><?php echo $roles[$v['roleid']]['name'];?></td>
                                <td><?php echo $v['mobile'];?></td>
                                <td><?php echo $v['email'];?></td>
                                <td><?php echo $operators[$v['operator']]['name'];?></td>
                                <td><?php echo $v['created'];?></td>
                                <td><?php echo Util_Tools::getStatus('user', $v['status']);?></td>
                                <td>
                                    <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
                                    <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
                                    <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
                                </td>
                              </tr>
                            <?php }?>
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
    <!-- Modal -->
    <form class="form-horizontal style-form" method="post" action="/">
        <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"> 添加权限 </h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-inline from-group">
                            <input type="text" name="email" placeholder="名称" autocomplete="off" class="form-control placeholder-no-fix">
                            <select class="form-control">
                                <option value='-1'>上级</option>
                                <option value='0'>一级</option>
                            </select>
                        </div>
                        <hr>
                        <div class="">
                            <label class="checkbox-inline"> 
                                <input type="checkbox" name="access" value="0"> 查
                            </label> 
                            <label class="checkbox-inline"> 
                                <input type="checkbox" name="access[]" value="1" checked> 增
                            </label> 
                            <label class="checkbox-inline"> 
                                <input type="checkbox" name="access[]" value="2"> 删
                            </label> 
                            <label class="checkbox-inline"> 
                                <input type="checkbox" name="access" value="3"> 改
                            </label> 
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button data-dismiss="modal" class="btn btn-default" type="button">关闭</button>
                        <button class="btn btn-theme" type="submit">提交</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
   <!-- modal -->

    <?php require $viewPath . "common/footer.phtml"?>
</section>
<?php require $viewPath . "common/js.phtml"?>
</body>
</html>
