<!DOCTYPE html>
<html lang="zh-CN">
   <?php require $viewPath . "common/head.phtml"?>
<body>
<section id="container" >
    <?php require $viewPath . "common/nav.phtml"?>
    <?php require $viewPath . "common/sidebar.phtml"?>
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            <div class="row mt">
                <div class="col-md-12">
                    <div class="content-panel">
                        <div class="clearfix"></div>
                        <h4><i class="fa fa-angle-right"></i>  系统公告列表
                        <?php if (isset($currentMenu[500401])) {?>
                        <button data-toggle="modal" href="#myModal" class="btn btn-primary pull-right nav-right">  添加 </button>
                        <?php }?>
                        </h4>
                        <hr>
                        <table class="table table-striped table-advance table-hover">
                        <thead>
                            <tr>
                                <th><i class="fa fa-flag"></i> 标题</th>
                                <th><i class="fa fa-user"></i> 添加人</th>
                                <th><i class="fa fa-user"></i> 内容简介</th>
                                <th><i class="fa fa-user"></i> 状态</th>
                                <th><i class="fa fa-clock-o"></i> 添加时间</th>
                                <th><i class="fa fa-cogs"> 操作</i></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($result as $k=>$v) {?>
                              <tr>
                                <td><?php echo $v['title'];?></td>
                                <td><?php echo $operators[$v['operator']]['name'];?></td>
                                <td><?php echo Util_Tools::subZh($v['content']);?></td>
                                <td><?php echo Util_Tools::getStatus('proclamation', $v['status']);?></td>
                                <td><?php echo $v['created'];?></td>
                                <td>
                                    <?php if (isset($currentMenu[500402]) && $v['status'] == 1) {?>
                                    <button class="btn btn-primary btn-xs modifyButton" data-id='<?php echo $v['id']?>' href="#modifyModal" title="修改"><i class="fa fa-pencil"></i></button>
                                    <?php }?>
                                    <?php if (isset($currentMenu[500405]) && $v['status'] == 1) {?>
                                    <button class="btn btn-info btn-xs sendButton" data-id='<?php echo $v['id']?>' href="#" title="发布"><i class="fa fa-send"></i></button>
                                    <?php }?>
                                    <?php if (isset($currentMenu[500406]) && $v['status'] == 2) {?>
                                    <button class="btn btn-warning btn-xs banButton" data-id='<?php echo $v['id']?>' href="#" title="撤回"><i class="fa fa-ban"></i></button>
                                    <?php }?>
                                    <?php if (isset($currentMenu[500404]) && $v['status'] != -1) {?>
                                    <button class="btn btn-danger btn-xs deleteButton" data-id='<?php echo $v['id']?>' href="#deleteModal" title="删除"><i class="fa fa-trash-o"></i></button>
                                    <?php }?>
                                    <?php if (isset($currentMenu[500404]) && $v['status'] == -1) {?>
                                    <button class="btn btn-danger btn-xs magicButton" data-id='<?php echo $v['id']?>' href="#magicModal" title="恢复"><i class="fa fa-magic"></i></button>
                                    <?php }?>
                                </td>
                              </tr>
                            <?php }?>
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
    <?php require $viewPath . "common/footer.phtml"?>
</section>
<!-- modal -->
<?php require $viewPath . "common/js.phtml"?>
<!-- Modal -->
<?php if (isset($currentMenu[500402])) {?>
<form class="form-horizontal style-form" id="form" onSubmit="return false;">
    <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  添加系统公告</h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <br />
                    <div class="">
                        <input type="text" name="title" placeholder="标题" autocomplete="off" class="form-control placeholder-no-fix">
                    </div>
                    <br />
                    <div class="">
                        <textarea name="content" placeholder="内容" autocomplete="off" class="form-control placeholder-no-fix" style="height: 245px;"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="submitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>

<?php if (isset($currentMenu[500403])) {?>
<form class="form-horizontal style-form" id="modifyForm" onSubmit="return false;">
    <input type="hidden" name='proclamationid'>
    <div aria-hidden="true" aria-labelledby="modifyModalLabel" role="dialog" tabindex="-1" id="modifyModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  修改系统公告</h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <br />
                    <div class="">
                        <input type="text" name="title" placeholder="标题" autocomplete="off" class="form-control placeholder-no-fix">
                    </div>
                    <br />
                    <div class="">
                        <textarea name="content" placeholder="内容" autocomplete="off" class="form-control placeholder-no-fix" style="height: 245px;"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="modifySubmitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>
<?php if (isset($currentMenu[500404])) {?>
<form class="form-horizontal style-form" id="deleteForm" onSubmit="return false;">
    <input type="hidden" name='proclamationid'>
    <div aria-hidden="true" aria-labelledby="modifyModalLabel" role="dialog" tabindex="-1" id="deleteModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  删除系统公告</h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <div>确定删除改公告吗?</div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="deleteSubmitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>
<?php if (isset($currentMenu[500405])) {?>
<form class="form-horizontal style-form" id="sendForm" onSubmit="return false;">
    <input type="hidden" name='proclamationid'>
    <input type="hidden" name='status' value='2'>
    <div aria-hidden="true" aria-labelledby="modifyModalLabel" role="dialog" tabindex="-1" id="sendModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  发布系统公告</h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <div>确定发布该公告吗?</div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="sendSubmitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>
<?php if (isset($currentMenu[500406])) {?>
<form class="form-horizontal style-form" id="banForm" onSubmit="return false;">
    <input type="hidden" name='proclamationid'>
    <input type="hidden" name='status' value='1'>
    <div aria-hidden="true" aria-labelledby="modifyModalLabel" role="dialog" tabindex="-1" id="banModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  撤回系统公告</h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <div>确定撤回该公告吗?</div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="banSubmitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>
<?php if (isset($currentMenu[500404])) {?>
<form class="form-horizontal style-form" id="magicForm" onSubmit="return false;">
    <input type="hidden" name='proclamationid'>
    <input type="hidden" name='status' value='1'>
    <div aria-hidden="true" aria-labelledby="modifyModalLabel" role="dialog" tabindex="-1" id="magicModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  恢复系统公告</h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <div>确定恢复该公告吗?</div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="magicSubmitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>
<script type="text/javascript" src="/public/js/base.js"></script>
<script>
function onComplete(result){
    if (result.status != 200) {
        $('.alert-warning').show();
        $('.showMsg').html(result.msg);
    } else {
        if (result.data.type == 'detail') {
            showDetail(result.data.list);
            return true;
        }
        location.href = "/sys/proclamation";
    }
}
function showDetail(data) {
    $('#modifyModal input[name="title"]').val(data.title);
    $('#modifyModal textarea[name="content"]').html(data.content);
}
$(document).ready(function(){
    $('#submitForm').click(function(){
        ajaxPost('/sys/proclamation/act/create', $("#form").serialize());
    });
    $('#modifySubmitForm').click(function(){
        ajaxPost('/sys/proclamation/act/modify', $("#modifyForm").serialize());
    });
    $(".modifyButton").click(function(){
        $('#modifyForm input[name="proclamationid"]').val($(this).attr('data-id'));
        ajaxPost("/sys/proclamation/act/get", {"id":$(this).attr('data-id')});
        $('#modifyModal').modal('show');
    });
    $('#deleteSubmitForm').click(function(){
        ajaxPost('/sys/proclamation/act/delete', $("#deleteForm").serialize());
    });
    $(".deleteButton").click(function(){
        $('#deleteForm input[name="proclamationid"]').val($(this).attr('data-id'));
        $('#deleteModal').modal('show');
    });

    $('#sendSubmitForm').click(function(){
        ajaxPost('/sys/proclamation/act/modify', $("#sendForm").serialize());
    });
    $(".sendButton").click(function(){
        $('#sendForm input[name="proclamationid"]').val($(this).attr('data-id'));
        $('#sendModal').modal('show');
    });

    $('#banSubmitForm').click(function(){
        ajaxPost('/sys/proclamation/act/modify', $("#banForm").serialize());
    });
    $(".banButton").click(function(){
        $('#banForm input[name="proclamationid"]').val($(this).attr('data-id'));
        $('#banModal').modal('show');
    });

    $('#magicSubmitForm').click(function(){
        ajaxPost('/sys/proclamation/act/modify', $("#magicForm").serialize());
    });
    $(".magicButton").click(function(){
        $('#magicForm input[name="proclamationid"]').val($(this).attr('data-id'));
        $('#magicModal').modal('show');
    });
})
</script>
</body>
</html>
