<!DOCTYPE html>
<html lang="zh-CN">
   <?php require $viewPath . "common/head.phtml"?>
<body>
<section id="container" >
    <?php require $viewPath . "common/nav.phtml"?>
    <?php require $viewPath . "common/sidebar.phtml"?>
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            <div class="row mt">
                <div class="col-md-12">
                    <div class="content-panel">
                        <div class="clearfix"></div>
                        <h4><i class="fa fa-angle-right"></i>  系统公告列表
                        <?php if (isset($currentMenu[200102])) {?>
                        <a href="/cases/create" class="btn btn-primary pull-right nav-right">  创建 </a>
                        <?php }?>
                        </h4>
                        <hr>
                        <table class="table table-striped table-advance table-hover">
                        <thead>
                            <tr>
                                <th><i class="fa fa-flag"></i> 标题</th>
                                <th><i class="fa fa-user"></i> 添加人</th>
                                <th><i class="fa fa-user"></i> 内容简介</th>
                                <th><i class="fa fa-user"></i> 状态</th>
                                <th><i class="fa fa-clock-o"></i> 添加时间</th>
                                <th><i class="fa fa-cogs"> 操作</i></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($result as $k=>$v) {?>
                              <tr>
                                <td><?php echo $v['title'];?></td>
                                <td><?php echo $operators[$v['operator']]['name'];?></td>
                                <td><?php echo Util_Tools::subZh($v['content']);?></td>
                                <td><?php echo Util_Tools::getStatus('proclamation', $v['status']);?></td>
                                <td><?php echo $v['created'];?></td>
                                <td>
                                    <?php if (isset($currentMenu[500402]) && $v['status'] == 1) {?>
                                    <button class="btn btn-primary btn-xs modifyButton" data-id='<?php echo $v['id']?>' href="#modifyModal" title="修改"><i class="fa fa-pencil"></i></button>
                                    <?php }?>
                                    <?php if (isset($currentMenu[500405]) && $v['status'] == 1) {?>
                                    <button class="btn btn-info btn-xs sendButton" data-id='<?php echo $v['id']?>' href="#" title="发布"><i class="fa fa-send"></i></button>
                                    <?php }?>
                                    <?php if (isset($currentMenu[500406]) && $v['status'] == 2) {?>
                                    <button class="btn btn-warning btn-xs banButton" data-id='<?php echo $v['id']?>' href="#" title="撤回"><i class="fa fa-ban"></i></button>
                                    <?php }?>
                                    <?php if (isset($currentMenu[500404]) && $v['status'] != -1) {?>
                                    <button class="btn btn-danger btn-xs deleteButton" data-id='<?php echo $v['id']?>' href="#deleteModal" title="删除"><i class="fa fa-trash-o"></i></button>
                                    <?php }?>
                                    <?php if (isset($currentMenu[500404]) && $v['status'] == -1) {?>
                                    <button class="btn btn-danger btn-xs magicButton" data-id='<?php echo $v['id']?>' href="#magicModal" title="恢复"><i class="fa fa-magic"></i></button>
                                    <?php }?>
                                </td>
                              </tr>
                            <?php }?>
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
    <?php require $viewPath . "common/footer.phtml"?>
</section>
<!-- modal -->
<?php require $viewPath . "common/js.phtml"?>
<!-- Modal -->
<script type="text/javascript" src="/public/js/base.js"></script>
</body>
</html>
