<!DOCTYPE html>
<html lang="zh-CN">
   <?php require $viewPath . "common/head.phtml"?>
<body>
<section id="container" >
    <?php require $viewPath . "common/nav.phtml"?>
    <?php require $viewPath . "common/sidebar.phtml"?>
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            <div class="row mt">
                <div class="col-md-12">
                    <div class="content-panel">
                        <h4><i class="fa fa-angle-right"></i> 案件类型</h4>
                        <hr>
                        <div class="form-inline">
                        <div class="btn-group pull-right nav-right">
                            <button type="button" class="btn btn-theme02"> 层级</button>
                            <button type="button" class="btn btn-theme02 dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="/cases/ctype/act/list?a-level=1"> 一</a></li>
                                <li><a href="/cases/ctype/act/list?a-level=2"> 二</a></li>
                                <li><a href="/cases/ctype/act/list?a-level=3"> 三</a></li>
                                <li><a href="/cases/ctype/act/list?a-level=4"> 四</a></li>
                                <li class="divider"></li>
                                <li><a href="/cases/ctype"> 清除</a></li>
                            </ul>
                        </div>
                        <div class="pull-right">
                            <input type="text" name="search" placeholder="名称" autocomplete="off" class="form-control placeholder-no-fix nav-right">
                            <button class="btn btn-primary pull-right nav-right" id="searchButton">  搜索</button>
                        </div>
                        <?php if (isset($currentMenu[200301])) {?>
                            <button data-toggle="modal" href="#myModal" class="btn btn-primary pull-right nav-right">  添加 </button>
                        <?php }?>
                        <br>
                        <br>
                        <hr>
                        <table class="table table-striped table-advance table-hover">
                        <thead>
                            <tr>
                                <th data-field="name"><i class="fa fa-bookmark"></i> 名称</th>
                                <th data-field="name"><i class="fa fa-bookmark"></i> 层级</th>
                                <th data-field="name"><i class="fa fa-bookmark"></i> 上级</th>
                                <th data-field="operator"><i class="fa fa-user"></i> 添加人</th>
                                <th data-field="created"><i class="fa fa-clock-o"></i> 添加时间</th>
                                <th><i class="fa fa-cogs"> 操作</i></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($result)){?>
                            <tr>
                                <td colspan="4" style="text-align:center"> 没有找到数据</td>
                            </tr>
                            <?php } else {
                                foreach ($result as $k=>$v) { 
                                    $datas = $v;
                                    $datas['parentname'] = isset($result[$v['parentid']]) ?  $result[$v['parentid']]['name'] : '无';
                            ?>
                            <tr>
                                <td><?php echo $v['name'];?></td>
                                <td><?php echo $v['level_zh'];?></td>
                                <td><?php echo  $datas['parentname'];?></td>
                                <td><?php echo $operators[$v['operator']]['name'];?></td>
                                <td><?php echo $v['created'];?></td>
                                <td>
                                    <button class="btn btn-primary btn-xs modifyButton" title="修改" datas='<?php echo json_encode($datas)?>'><i class="fa fa-pencil"></i></button>
                                </td>
                            </tr>
                            <?php }}?>
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
    <?php require $viewPath . "common/footer.phtml"?>
</section>
<?php require $viewPath . "common/js.phtml"?>
<?php if (isset($currentMenu[200303])) {?>
<form class="form-horizontal style-form" id="modifyForm" onSubmit="return false;">
    <div aria-hidden="true" aria-labelledby="modifyModalLabel" role="dialog" tabindex="-1" id="modifyModal" class="modal fade">
        <input type="hidden" name="id">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  修改案件类型 </h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <br />
                    <div class="from-group form-inline">
                        <input type="text" name="name" placeholder="名称" autocomplete="off" class="form-control placeholder-no-fix">
                        <div class="btn-group">
                            <input type="hidden" name="level" id="level">
                            <button type="button" class="btn btn-theme03" id="level-btn">层级</button>
                            <button type="button" class="btn btn-theme03 dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a class="a-level" data-id="1" href="#bottom"> 一 </a></li>
                                <li><a class="a-level" data-id="2" href="#bottom"> 二 </a></li>
                                <li><a class="a-level" data-id="3" href="#bottom"> 三 </a></li>
                                <li><a class="a-level" data-id="4" href="#bottom"> 四 </a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <input type="hidden" name="parentid" id="parentid">
                            <button type="button" class="btn btn-theme03" id="parent-btn">上级</button>
                            <button type="button" class="btn btn-theme03 dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only"></span>
                            </button>
                            <ul class="dropdown-menu pLevel" role="menu">
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="modifySubmitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>

<?php if (isset($currentMenu[200302])) {?>
<form class="form-horizontal style-form" id="form" onSubmit="return false;">
    <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  添加案件类型 </h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <br />
                    <div class="from-group form-inline">
                        <input type="text" name="name" placeholder="名称" autocomplete="off" class="form-control placeholder-no-fix">
                        <div class="btn-group">
                            <input type="hidden" name="level" id="level">
                            <button type="button" class="btn btn-theme03" id="level-btn">层级</button>
                            <button type="button" class="btn btn-theme03 dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a class="a-level" data-id="1" href="#bottom"> 一 </a></li>
                                <li><a class="a-level" data-id="2" href="#bottom"> 二 </a></li>
                                <li><a class="a-level" data-id="3" href="#bottom"> 三 </a></li>
                                <li><a class="a-level" data-id="4" href="#bottom"> 四 </a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <input type="hidden" name="parentid" id="parentid">
                            <button type="button" class="btn btn-theme03" id="parent-btn">上级</button>
                            <button type="button" class="btn btn-theme03 dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only"></span>
                            </button>
                            <ul class="dropdown-menu pLevel" role="menu">
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="submitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>
<script type="text/javascript" src="/public/js/base.js"></script>
<script>
function onComplete(result){
    if (result.status != 200) {
        $('.alert-warning').show();
        $('.showMsg').html(result.msg);
        $('.pLevel').html('');
    } else {
        if (result.data.type == 'level'){
            showLevelHtml(result.data.list);
            return true;
        } else if (result.data != "") {
            $('#showPassMsg').html(result.data);
            $('#myModal').modal('hide');
            $('#showPassModal').modal('show');
            return true;
        }
        location.href = "/cases/ctype";
    }
}
function showLevelHtml(data) {
    var obj = $('.pLevel');
    obj.html('')
    for (i in data){
        var html = '';
        html = '<li><a class="a-parent"  href="#bottom" onClick="choosParent(\'' + data[i].id + '\', \'' + data[i].name + '\')"> ' + data[i].name + ' </a></li>';
        obj.append(html);
    }
}

function choosParent(parentid, name) {
    $('#myModal #parent-btn').html(name);
    $('#myModal #parentid').val(parentid);
    $('#modifyModal #parent-btn').html(name);
    $('#modifyModal #parentid').val(parentid);
}

$(document).ready(function(){
    $("#searchButton").click(function(){
        var value = $("input[name='search']").val();
        if (value == "") {
            $("#noticeMsg").html("搜索内容不能为空");
            $('#noticeModal').modal('show');
            return false;
        }
        location.href = "/cases/ctype/act/list?search=" + value;

    });
    $('#submitForm').click(function(){
        ajaxPost('/cases/ctype/act/create', $("#form").serialize());
    });
    $('#modifySubmitForm').click(function(){
        ajaxPost('/cases/ctype/act/modify', $("#modifyForm").serialize());
    });
    $("#myModal .a-level").click(function(){
        var value = $(this).html();
        var level= $(this).attr('data-id');
        $('#myModal #level-btn').html(value);
        $('#myModal #level').val(level);
        if (level == 1) {
            $('.pLevel').html('');
        } else {
            $('#myModal #parent-btn').html('上级');
            $('.pLevel').html('');
            ajaxPost('/cases/ctype/act/getList', {'level':level});
        }
    });

    $(".modifyButton").click(function(){
        var datas = $.parseJSON($(this).attr('datas'));
        $('#modifyModal input[name="id"]').val(datas.id);
        $('#modifyModal input[name="name"]').val(datas.name);

        $('#modifyModal input[name="level"]').val(datas.level);
        $('#modifyModal #level-btn').html(datas.level_zh);

        $('#modifyModal input[name="parentid"]').val(datas.parentid);
        $('#modifyModal #parent-btn').html(datas.parentname);
        if (datas.level != 1){
            ajaxPost('/cases/ctype/act/getList', {'level': datas.level});
        }
        $('#modifyModal').modal('show');
    });
    $("#modifyModal .a-level").click(function(){
        var value = $(this).html();
        var level= $(this).attr('data-id');
        $('#modifyModal #level-btn').html(value);
        $('#modifyModal #level').val(level);
        if (level == 1) {
            $('.pLevel').html('');
        } else {
            $('#modifyModal #parent-btn').html('上级');
            $('.pLevel').html('');
            ajaxPost('/cases/ctype/act/getList', {'level':level});
        }
    });
})
</script>
</body>
</html>
