<!DOCTYPE html>
<html lang="zh-CN">
   <?php require $viewPath . "common/head.phtml"?>
<body>
<section id="container" >
    <?php require $viewPath . "common/nav.phtml"?>
    <?php require $viewPath . "common/sidebar.phtml"?>
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            <div class="row mt">
                <div class="col-md-12">
                    <div class="content-panel">
                        <div class="clearfix"></div>
                        <h4><i class="fa fa-angle-right"></i>  案件列表
                        <?php if (isset($currentMenu[200102])) {?>
                        <a href="/cases/create" class="btn btn-primary pull-right nav-right">  创建 </a>
                        <?php }?>
                        </h4>
                        <hr>
                        <table class="table table-striped table-advance table-hover">
                        <thead>
                            <tr>
                                <th><i class="fa fa-flag"></i> 案号</th>
                                <th><i class="fa fa-user-secret"></i> 指导律师</th>
                                <th><i class="fa fa-user-plus"></i> 经办律师</th>
                                <th><i class="fa fa-flag"></i> 案件类型</th>
                                <th><i class="fa fa-comment"></i> 案由</th>
                                <th><i class="fa fa-flag"></i> 阶段</th>
                                <th><i class="fa fa-list"></i> 相关文件</th>
                                <th><i class="fa fa-calendar-times-o"></i> 时间计划</th>
                                <th><i class="fa fa-clock-o"></i> 添加时间</th>
                                <th><i class="fa fa-user"></i> 添加人</th>
                                <th><i class="fa fa-cogs"> 操作</i></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($result as $k=>$v) {?>
                              <tr>
                                <td><?php echo $v['title'];?></td>
                                <td><?php echo $users[$v['guide_user']]['name'];?></td>
                                <td><?php echo $users[$v['handle_user']]['name'];?></td>
                                <td><?php foreach ($v['type'] as $type){echo $types[$type]['name'];echo "<br>";}?></td>
                                <td><?php echo $v['cases_reason'];?></td>
                                <td><?php echo $flag[$v['cases_flag']]['name'];?></td>
                                <td><?php echo $v['files']?></td>
                                <td><?php foreach($v['timeline'] as $vv){
                                    echo $vv['name'];
                                    echo "  ";
                                    echo date("Y-m-d H:i", strtotime($vv['time']));
                                    echo "<br>";
                                }
                                ?></td>
                                <td><?php echo $v['created'];?></td>
                                <td><?php echo $users[$v['user_id']]['name'];?></td>
                                <td>
                                    <a class="btn btn-info btn-xs" href="/cases/info/id/<?php echo $v['id']?>" title="查看"><i class="fa fa-eye"></i></a>
                                    <a class="btn btn-primary btn-xs modifyButton" href="/cases/modify/id/<?php echo $v['id']?>" title="修改"><i class="fa fa-pencil"></i></a>
                                    <button class="btn btn-danger btn-xs magicButton" data-id='<?php echo $v['id']?>' href="#magicModal" title="恢复"><i class="fa fa-magic"></i></button>
                                </td>
                              </tr>
                            <?php }?>
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
    <?php require $viewPath . "common/footer.phtml"?>
</section>
<!-- modal -->
<?php require $viewPath . "common/js.phtml"?>
<!-- Modal -->
<script type="text/javascript" src="/public/js/base.js"></script>
</body>
</html>
