<!DOCTYPE html>
<html lang="zh-CN">
   <?php require $viewPath . "common/head.phtml"?>
    <link href="/public/js/bootstrap-fileinput/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/public/js/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
<body>
<section id="container" >
    <?php require $viewPath . "common/nav.phtml"?>
    <?php require $viewPath . "common/sidebar.phtml"?>
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            <div class="row mt">
                <div class="col-lg-12">
                    <div class="form-panel">
                    <h4><i class="fa fa-angle-right"></i> 案件信息</h4>
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <hr>
                    <form class="form-horizontal style-form" onSubmit="return false" id="form" enctype="multipart/form-data">
                    <input name="casesid" value="<?php echo $list['id']?>" type="hidden">
                    <?php if (!empty($info['files'])) {?>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">相关文件</label>
                        <div class="col-sm-10">
                            <?php 
                                $min = 0;
                                foreach ($info['files'] as $v) {
                                    if ($v['need'] == 1) {
                                        $class = "text-danger";
                                        $min++;
                                    } else {
                                        $class = "text-info";
                                    }
                            ?>
                            <label class="control-label <?php echo $class?>"><?php echo $v['name'];?>(<?php echo $v['need'] == 1 ? "必填" : "选填"?>)</label>
                            <br>
                            <?php }?>
                            <input id="file-all" type="file" multiple class="file" name="files" data-overwrite-initial="false" data-min-file-count="<?php echo $min;?>">
                        </div>
                    </div>
                    <?php }?>
                    <div class="form-group form-inline">
                       <label class="col-sm-1 control-label"> 时间计划 </label>
                       <div class="col-sm-10">
                            <div id="timeline">
                                <input type="text" name="times[]" class="form-control place holder-no-fix"  placeholder="事件说明" autocomplete="off" style="width:39%">
                                <div class="input-group date form_datetime col-md-5" data-link-field="dtp_input1">
                                    <input class="form-control" size="16" type="text" value="" readonly>
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
	                                <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                                </div>
                                <input type="hidden" id="dtp_input1" value="" name="date[]"/><br/><br/>
                            </div>
                            <button type="button" class="btn btn-theme04" id="addButton">增加</button>
                        </div>
                    </div>
                    <div class="form-group form-inline">
                       <label class="col-sm-2 control-label">案件受理机关</label>
                       <div class="col-sm-4">
                            <input type="text" name="operator[com]" class="form-control holder-no-fix"  placeholder="姓名/企业名称" autocomplete="off">
                        </div>
                       <label class="col-sm-2 control-label">案件经办人员</label>
                       <div class="col-sm-4">
                            <input type="text" name="operator[peo]" class="form-control holder-no-fix"  placeholder="姓名/企业名称" autocomplete="off">
                        </div>
                    </div>

                    <div class="form-group centered">
                        <button type="button" class="btn btn-theme03" id="saveButton">保存</button>
                    </div> 
                    <!--div class="from-group btn-group btn-group-justified">
                          <div class="btn-group">
                            <button type="button" class="btn btn-theme04" id="saveButton">保存</button>
                          </div>
                          <div class="btn-group">
                            <button type="button" class="btn btn-theme02" id="nextButton">下一步</button>
                          </div>
                          <div class="btn-group">
                            <button type="button" class="btn btn-theme03" id="submitButton">结束</button>
                          </div>
                        </div>
                    </div--->
                    </form>
                </div>
            </div>
        </section>
    </section>
    <?php require $viewPath . "common/footer.phtml"?>
</section>

<?php require $viewPath . "common/js.phtml"?>
<script src="/public/js/bootstrap-fileinput/js/fileinput.min.js" type="text/javascript" charset="UTF-8"></script>
<script src="/public/js/bootstrap-fileinput/js/locales/zh.js" type="text/javascript" charset="UTF-8"></script>
<script type="text/javascript" src="/public/js/base.js"></script>
<script type="text/javascript" src="/public/js/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js" charset="UTF-8"></script>
<script type="text/javascript" src="/public/js/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>
<script>

function onComplete(result) {
    if (result.status != 200) {
        $('.alert-warning').show();
        $('.showMsg').html(result.msg);
    } else {
        location.href="/cases/list"
    }
}
$("#file-all").fileinput({
    language: 'zh',
    uploadUrl: '/cases/upload', 
    uploadExtraData: {id: <?php echo $list['id']?>, f: <?php echo $list['cases_flag']?>},
    //allowedFileExtensions : ['jpg', 'png','gif'],
    overwriteInitial: false,
    //maxFileSize: 1000,
    maxFilesNum: 10,
    //allowedFileTypes: ['image', 'video', 'flash'],
    fileType: "any",
    previewFileIcon: "<i class='glyphicon glyphicon-king'></i>",
    slugCallback: function(filename) {
        return filename.replace('(', '_').replace(']', '_');
    }
});
var files = [];
$("#file-all").on("fileuploaded", function(event, data, previewId, index) {
    var response = data.response;
    var filename = response.data;
    files.push(filename);
});
$('.form_datetime').datetimepicker({
    language: 'zh-CN',
    weekStart: 1,
    todayBtn:  1,
	autoclose: 1,
	todayHighlight: 1,
	startView: 2,
	forceParse: 0,
    showMeridian: 1,
    format: 'yyyy-mm-dd hh:ii'
});
$(document).ready(function(){
    $("#saveButton").click(function(){
        var jsonData = $("#form").serializeArray();
        var len = jsonData.length
        jsonData[len+1] = {'name':'files', 'value':files};
        ajaxPost('/cases/submit', jsonData);
    });
    $('.form_datetime').live('click', function(){
        $('.form_datetime').datetimepicker({
            language: 'zh-CN',
            weekStart: 1,
            todayBtn:  1,
	        autoclose: 1,
	        todayHighlight: 1,
	        startView: 2,
	        forceParse: 0,
            showMeridian: 1,
            format: 'yyyy-mm-dd hh:ii'
        });
    });
    $("#addButton").click(function(){
        var id = $("#timeline").children('div').length + 1;
        var html = '<input type="text" name="times[]" class="form-control place holder-no-fix"  placeholder="事件说明" autocomplete="off" style="width:39%">'+
                   '<div class="input-group date form_datetime col-md-5" data-link-field="dt'+id+'">'+
                        '<input class="form-control" size="16" type="text" value="" readonly>'+
                        '<span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>'+
	                    '<span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>'+
                   '</div>'+
                   '<input type="hidden" id="dt' + id +'" value="" name="date[]" /><br/><br/>'
        $("#timeline").append(html); 
    });
});
</script>
</body>
</html>
