<!DOCTYPE html>
<html lang="zh-CN">
   <?php require $viewPath . "common/head.phtml"?>
<body>
<section id="container" >
    <?php require $viewPath . "common/nav.phtml"?>
    <?php require $viewPath . "common/sidebar.phtml"?>
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            <div class="row mt">
                <div class="col-lg-12">
                    <div class="form-panel">
                    <h4>
                        <i class="fa fa-angle-right"></i> 个人信息
                        <?php if (isset($currentMenu[400103])) {?>
                        <button class="btn btn-primary pull-right nav-right" id="modifyButton"> 修改</button>
                        <?php }?>
                    </h4>
                    <hr>
                    <form class="form-horizontal style-form">
                        <div class="form-group">
                            <label class="col-sm-2 col-sm-2 control-label">姓名</label>
                            <div class="col-sm-10">
                                <?php echo $result['name'];?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-sm-2 control-label">性别</label>
                            <div class="col-sm-10">
                                <?php echo $result['gender'];?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-sm-2 control-label">职位</label>
                            <div class="col-sm-10">
                                <?php echo $duties[$result['duties']]['name'];?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-sm-2 control-label">角色</label>
                            <div class="col-sm-10">
                                <?php echo $roles[$result['roleid']]['name'];?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-sm-2 control-label">电话</label>
                            <div class="col-sm-10">
                                <?php echo $result['mobile'];?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-sm-2 control-label">邮箱</label>
                            <div class="col-sm-10">
                                <?php echo $result['email'];?>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </section>
    <?php require $viewPath . "common/footer.phtml"?>
</section>
<?php require $viewPath . "common/js.phtml"?>
<?php if (isset($currentMenu[400103])) {?>
<form class="form-horizontal style-form" id="modifyForm" onSubmit="return false;">
    <div aria-hidden="true" aria-labelledby="modifyModalLabel" role="dialog" tabindex="-1" id="modifyModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">  修改用户 </h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-warning">
                        <strong> 警告！</strong><span class="showMsg"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">姓名</label>
                        <div class="col-sm-10">
                            <input type="text" name="name" value="<?php echo $result['name']?>" placeholder="姓名" autocomplete="off" class="form-control placeholder-no-fix">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">电话</label>
                        <div class="col-sm-10">
                            <input type="text" name="mobile" value="<?php echo $result['mobile']?>" placeholder="电话" autocomplete="off" class="form-control placeholder-no-fix">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">邮箱</label>
                        <div class="col-sm-10">
                            <input type="text" name="email" value="<?php echo $result['email']?>" placeholder="邮箱" autocomplete="off" class="form-control placeholder-no-fix">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-sm-2 control-label">性别</label>
                        <div class="btn-group">
                            <input type="hidden" name="gender" id="gender" value="<?php echo $result['gender']?>">
                            <button type="button" class="btn btn-theme03" id="gender-btn"><?php echo $result['gender']?></button>
                            <button type="button" class="btn btn-theme03 dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a class="a-gender" data-id="男" href="#bottom">男</a></li>
                                <li><a class="a-gender" data-id="女" href="#bottom">女</a></li>
                            </ul>
                        </div>
                    </div>
                    <br />
                    <br />
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button class="btn btn-theme" id="modifySubmitForm">提交</button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php }?>
<script type="text/javascript" src="/public/js/base.js"></script>
<script>
function onComplete(result){
    if (result.status != 200) {
        $('.alert-warning').show();
        $('.showMsg').html(result.msg);
    } else {
        location.href = "/setting/profile";
    }
}
$(document).ready(function(){
    $('#modifySubmitForm').click(function(){
        ajaxPost('/setting/modify', $("#modifyForm").serialize());
    });
    $("#modifyModal .a-gender").click(function(){
        var value = $(this).html();
        var gender = $(this).attr('data-id');
        $('#modifyModal #gender-btn').html(value);
        $('#modifyModal #gender').val(gender);
    });
    $("#modifyButton").click(function(){
        $('#modifyModal').modal('show');
    });
});
</script>
</body>
</html>
